<a href="https://colab.research.google.com/github/harshal1507/python/blob/main/Python_IMP_Libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Library - Numerical Python**

Advantages of Numpy Arrays

1. Allows several Mathematical Operations
2. Faster Operations

In [32]:
import numpy as np

List vs Numpy - Time Taken

In [ ]:
from time import process_time

Time taken by list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.0012897119999992768


Time taken by Numpy array

In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)

0.00039671399999718915


Numpy Arrays

In [ ]:
# list
list = [1,2,3,4,5]
print(list)
type(list)

[1, 2, 3, 4, 5]


list

In [ ]:
# numpy array
numpy_array = [1,2,3,4,5]
print(numpy_array)
type(numpy_array)

[1, 2, 3, 4, 5]


list

In [ ]:
# 1 dimensional array
a = np.array([1,3,4,5,3])
print(a.shape)

b = np.array([(2,43,5,2,2,5,2),(2,24,3,6,4,2,7)])
print(b.shape)

c = np.array([(2,43,5,2,2,5,2),(2,24,3,6,4,2,7)], dtype=float)
print(c)

(5,)
(2, 7)
[[ 2. 43.  5.  2.  2.  5.  2.]
 [ 2. 24.  3.  6.  4.  2.  7.]]


Initial Placeholders in Numpy Array

In [ ]:
# array of zeros
nparray1 = np.zeros((4,5))
print(nparray1)

# array of ones
nparray2 = np.ones((3,3))
print(nparray2)

# array of particular value
nparray3 = np.full((3,3),100)
print(nparray3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [ ]:
# Identity matrix = diagonal values are one
nparray4 = np.eye(5)
print(nparray4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# create a numpy with random values
npram1 = np.random.random((3,4))
print(npram1)

# create a numpy with random values within specific range
npram2 = np.random.randint(10,100,(3,5))
print(npram2)

[[0.4011204  0.08861514 0.41455404 0.64541205]
 [0.20604271 0.52627271 0.16404969 0.09964426]
 [0.51316106 0.7250021  0.53440531 0.60162068]]
[[92 80 91 67 86]
 [47 88 59 38 65]
 [12 64 23 42 20]]


In [ ]:
# array of an evenly spaced values --> specifying the number of values required
nparray5 = np.linspace(10,30,6)
print(nparray5)

[10. 14. 18. 22. 26. 30.]


In [ ]:
# array of an evenly spaced values --> specifying the step
nparray6 = np.arange(10,30,5)
print(nparray6)

[10 15 20 25]


In [ ]:
# list to a numpy array
# similarly tuple can be converted to numpy array
list2 = [3,5,2,2,4]
nparray7 = np.asarray(list2)

print(nparray7)
type(nparray7)

[3 5 2 2 4]


numpy.ndarray

# Analysing a Numpy Array

In [ ]:
nparray8 = np.random.randint(10,90,(5,5))
print(nparray8)

[[62 83 26 44 85]
 [50 73 21 56 53]
 [55 84 55 84 80]
 [19 84 23 83 31]
 [60 64 62 41 41]]


In [ ]:
# array dimension
print(nparray8.shape)

(5, 5)


In [ ]:
# number of dimensions
print(nparray8.ndim)

2


In [ ]:
# number of elements in an array
print(nparray8.size)

25


In [ ]:
# checking the datatype of values in an array
print(nparray8.dtype)

int64


# Mathematical Operations on an Numpy Array

In [ ]:
list1 = [2,5,2,6,7]
list2 = [3,5,6,2,2]
print(list1 + list2)

[2, 5, 2, 6, 7, 3, 5, 6, 2, 2]


In [ ]:
np1 = np.random.randint(10,30,(3,3))
np2 = np.random.randint(30,60,(3,3))

print(np1)
print(np2)

[[12 21 19]
 [19 22 21]
 [15 18 25]]
[[33 44 58]
 [55 40 42]
 [40 33 46]]


In [ ]:
print(np1+np2)
print(np1-np2)
print(np1*np2)
print(np1/np2)

print(np.add(np1,np2))
print(np.subtract(np1,np2))
print(np.multiply(np1,np2))
print(np.divide(np1,np2))

[[45 65 77]
 [74 62 63]
 [55 51 71]]
[[-21 -23 -39]
 [-36 -18 -21]
 [-25 -15 -21]]
[[ 396  924 1102]
 [1045  880  882]
 [ 600  594 1150]]
[[0.36363636 0.47727273 0.32758621]
 [0.34545455 0.55       0.5       ]
 [0.375      0.54545455 0.54347826]]
[[45 65 77]
 [74 62 63]
 [55 51 71]]
[[-21 -23 -39]
 [-36 -18 -21]
 [-25 -15 -21]]
[[ 396  924 1102]
 [1045  880  882]
 [ 600  594 1150]]
[[0.36363636 0.47727273 0.32758621]
 [0.34545455 0.55       0.5       ]
 [0.375      0.54545455 0.54347826]]


# Array Manipulation

In [4]:
arrman = np.random.randint(0,10,(2,3))
print(arrman)
print(arrman.shape)

[[3 0 6]
 [7 1 2]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(arrman)
print(trans)
print(trans.shape)

# another method of transpose
trans2 = arrman.T
print(trans2)
print(trans2.shape)

[[5 3]
 [9 3]
 [1 0]]
(3, 2)
[[5 3]
 [9 3]
 [1 0]]
(3, 2)


In [ ]:
# reshaping array
a = np.random.randint(0,10,(2,3))
b = a.reshape(3,2)
print(a)
print(a.shape)
print(b)
print(b.shape)

[[6 3 1]
 [6 6 4]]
(2, 3)
[[6 3]
 [1 6]
 [6 4]]
(3, 2)


# **Pandas Library**

Useful for Data Processing and Analysis

Pandas Data Frame
Pandas DataFrame is two dimesional tabular data structure with labelled axes (rows and columns)

In [20]:
# importing pandas library
import pandas as pd

from google.colab import data_table
from vega_datasets import data

data_table.enable_dataframe_formatter()

data.airports()

iata                       name              city state country  \
0     00M                    Thigpen       Bay Springs    MS     USA   
1     00R       Livingston Municipal        Livingston    TX     USA   
2     00V                Meadow Lake  Colorado Springs    CO     USA   
3     01G               Perry-Warsaw             Perry    NY     USA   
4     01J           Hilliard Airpark          Hilliard    FL     USA   
...   ...                        ...               ...   ...     ...   
3371  ZEF            Elkin Municipal             Elkin    NC     USA   
3372  ZER  Schuylkill Cty/Joe Zerbey        Pottsville    PA     USA   
3373  ZPH      Zephyrhills Municipal       Zephyrhills    FL     USA   
3374  ZUN                 Black Rock              Zuni    NM     USA   
3375  ZZV       Zanesville Municipal        Zanesville    OH     USA   

       latitude   longitude  
0     31.953765  -89.234505  
1     30.685861  -95.017928  
2     38.945749 -104.569893  
3     42.741347  -78.052081  
4     30.688012  -81.905944  
...         ...         ...  
3371  36.280024  -80.786069  
3372  40.706449  -76.373147  
3373  28.228065  -82.155916  
3374  35.083227 -108.791777  
3375  39.944458  -81.892105  

[3376 rows x 7 columns]

In [7]:
# creating pandas dataframe

from sklearn.datasets import load_diabetes

In [8]:
diabetes_dataset = load_diabetes()
type(diabetes_dataset)

sklearn.utils._bunch.Bunch

In [9]:
print(diabetes_dataset)

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]]), 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
  

In [23]:
# pandas dataframe
db_data = pd.DataFrame(diabetes_dataset.data, columns = diabetes_dataset.feature_names)
db_data.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019907 -0.017646  
1 -0.039493 -0.068332 -0.092204  
2 -0.002592  0.002861 -0.025930  
3  0.034309  0.022688 -0.009362  
4 -0.002592 -0.031988 -0.046641

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['age'].plot(kind='hist', bins=20, title='age')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['sex'].plot(kind='hist', bins=20, title='sex')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['bmi'].plot(kind='hist', bins=20, title='bmi')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='index', y='age', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='age', y='sex', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='sex', y='bmi', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='bmi', y='bp', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['age']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('age')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['sex']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('sex')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['bmi']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('bmi')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['bp']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('bp')

from matplotlib import pyplot as plt
_df_12['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_13['age'].plot(kind='line', figsize=(8, 4), title='age')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_14['sex'].plot(kind='line', figsize=(8, 4), title='sex')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_15['bmi'].plot(kind='line', figsize=(8, 4), title='bmi')
plt.gca().spines[['top', 'right']].set_visible(False)

In [24]:
db_data.shape

(442, 10)

In [27]:
# data from csv file
csv_data = pd.read_csv('/content/sample_data/california_housing_test.csv')
csv_data.head()

# for excel use pd.read_excel('path')

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0

In [28]:
type(csv_data)

pandas.core.frame.DataFrame

In [29]:
csv_data.shape

(3000, 9)

In [31]:
# exporting data frame to file
csv_data_file = csv_data.to_csv('test_data.csv')
excel_data_file = csv_data.to_excel('test_data_excel.xlsx')

In [42]:
# creating dataframe with random values
random_df = pd.DataFrame(np.random.rand(20,10))
random_df.head()

0         1         2         3         4         5         6  \
0  0.297194  0.272584  0.987832  0.015841  0.175240  0.536623  0.459744   
1  0.910600  0.618713  0.032119  0.456469  0.821550  0.916112  0.802797   
2  0.461302  0.072636  0.264902  0.193636  0.831756  0.472431  0.813019   
3  0.046520  0.184591  0.261959  0.325719  0.837390  0.460901  0.320720   
4  0.676562  0.888334  0.111176  0.049110  0.707750  0.877930  0.370338   

          7         8         9  
0  0.779821  0.965042  0.335277  
1  0.514673  0.185893  0.758234  
2  0.298101  0.977749  0.926879  
3  0.129337  0.801626  0.374325  
4  0.540703  0.836097  0.625095

In [43]:
random_df.shape

(20, 10)

Inspecting a dataframe

In [44]:
# finding the number of rows and columns
random_df.shape

(20, 10)

In [45]:
# first 5 rows in dataframe
random_df.head()

0         1         2         3         4         5         6  \
0  0.297194  0.272584  0.987832  0.015841  0.175240  0.536623  0.459744   
1  0.910600  0.618713  0.032119  0.456469  0.821550  0.916112  0.802797   
2  0.461302  0.072636  0.264902  0.193636  0.831756  0.472431  0.813019   
3  0.046520  0.184591  0.261959  0.325719  0.837390  0.460901  0.320720   
4  0.676562  0.888334  0.111176  0.049110  0.707750  0.877930  0.370338   

          7         8         9  
0  0.779821  0.965042  0.335277  
1  0.514673  0.185893  0.758234  
2  0.298101  0.977749  0.926879  
3  0.129337  0.801626  0.374325  
4  0.540703  0.836097  0.625095

In [46]:
# last 5 rows of dataframe
random_df.tail()

0         1         2         3         4         5         6  \
15  0.000959  0.619009  0.877396  0.571290  0.196430  0.046732  0.866644   
16  0.362171  0.325547  0.877789  0.942136  0.658607  0.646763  0.186564   
17  0.630036  0.883657  0.019183  0.402281  0.375314  0.500832  0.391569   
18  0.759411  0.163226  0.844978  0.703800  0.918035  0.813296  0.678641   
19  0.044756  0.175752  0.897562  0.609511  0.067135  0.069248  0.131430   

           7         8         9  
15  0.416369  0.668187  0.164288  
16  0.839415  0.543300  0.908662  
17  0.438621  0.271242  0.235401  
18  0.034262  0.900117  0.311890  
19  0.407667  0.416038  0.304234

In [47]:
# informations about dataframe
csv_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB


In [48]:
# finding number of missing values
csv_data.isnull()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0         False     False               False        False           False   
1         False     False               False        False           False   
2         False     False               False        False           False   
3         False     False               False        False           False   
4         False     False               False        False           False   
...         ...       ...                 ...          ...             ...   
2995      False     False               False        False           False   
2996      False     False               False        False           False   
2997      False     False               False        False           False   
2998      False     False               False        False           False   
2999      False     False               False        False           False   

      population  households  median_income  median_house_value  
0          False       False          False               False  
1          False       False          False               False  
2          False       False          False               False  
3          False       False          False               False  
4          False       False          False               False  
...          ...         ...            ...                 ...  
2995       False       False          False               False  
2996       False       False          False               False  
2997       False       False          False               False  
2998       False       False          False               False  
2999       False       False          False               False  

[3000 rows x 9 columns]

In [49]:
csv_data.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [50]:
csv_data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0

In [53]:
# counting the values based on labels
csv_data.value_counts('housing_median_age').sum()
csv_data.value_counts('housing_median_age')

housing_median_age
52.0    173
35.0    118
36.0    115
16.0    107
34.0    102
17.0    100
32.0     91
26.0     88
37.0     88
25.0     86
33.0     85
15.0     77
18.0     76
19.0     76
30.0     76
29.0     75
24.0     75
27.0     74
38.0     64
20.0     63
21.0     61
22.0     60
28.0     58
14.0     57
31.0     57
43.0     56
41.0     56
39.0     55
23.0     53
44.0     51
42.0     51
45.0     51
40.0     43
11.0     41
12.0     41
13.0     41
46.0     41
5.0      39
48.0     34
10.0     30
4.0      28
9.0      27
6.0      25
8.0      25
47.0     22
49.0     21
7.0      20
50.0     16
3.0      12
51.0     11
2.0       6
1.0       2
Name: count, dtype: int64

In [55]:
# Grouping the values based on labels
csv_data.groupby('housing_median_age').mean()

longitude   latitude  total_rooms  total_bedrooms  \
housing_median_age                                                       
1.0                -117.450000  34.470000    44.500000        8.500000   
2.0                -119.596667  35.793333  9006.333333     1459.166667   
3.0                -119.389167  35.591667  6731.250000     1214.750000   
4.0                -118.963571  34.962857  7383.392857     1385.214286   
5.0                -119.550513  35.870769  5660.615385     1085.051282   
6.0                -119.419600  35.573200  5255.040000     1001.400000   
7.0                -118.853000  35.096500  3718.250000      646.500000   
8.0                -118.952000  35.499200  3311.520000      617.240000   
9.0                -119.241111  35.755556  3407.888889      646.111111   
10.0               -119.763667  36.084000  3294.500000      671.166667   
11.0               -119.400732  35.748780  3483.170732      703.146341   
12.0               -119.129268  35.385122  4032.731707      810.341463   
13.0               -119.168049  35.710244  3343.243902      659.975610   
14.0               -119.882105  36.494561  3229.807018      649.210526   
15.0               -119.554156  36.032727  3171.727273      571.753247   
16.0               -119.667477  35.860280  2609.971963      494.775701   
17.0               -119.900400  36.382200  3393.910000      641.200000   
18.0               -119.794868  35.955921  3152.671053      617.934211   
19.0               -119.415921  35.749474  3286.565789      713.736842   
20.0               -119.956825  36.117460  3219.936508      623.936508   
21.0               -120.049016  35.992623  3068.393443      648.819672   
22.0               -120.099500  36.115167  2915.950000      604.583333   
23.0               -119.659623  35.633396  2879.037736      580.528302   
24.0               -119.375867  35.507200  2948.733333      592.506667   
25.0               -119.526860  35.641279  2882.813953      561.104651   
26.0               -119.571705  35.486591  2562.784091      506.534091   
27.0               -119.247027  35.169459  2647.878378      553.337838   
28.0               -119.263621  35.301379  2493.810345      576.258621   
29.0               -119.692533  35.623733  2524.306667      554.240000   
30.0               -119.249605  35.254342  2252.855263      495.184211   
31.0               -119.516491  35.518772  2121.421053      464.859649   
32.0               -119.427473  35.486484  2215.274725      452.054945   
33.0               -119.374235  35.334706  2241.188235      476.058824   
34.0               -119.253725  35.124804  2213.245098      430.039216   
35.0               -119.362288  35.203644  1958.398305      397.694915   
36.0               -119.292087  35.163913  1783.669565      376.930435   
37.0               -119.446477  35.447500  1825.636364      378.068182   
38.0               -119.527031  35.524687  1796.984375      382.921875   
39.0               -119.607455  35.473091  1900.872727      429.745455   
40.0               -119.548140  35.410465  1697.813953      364.930233   
41.0               -119.570179  35.367321  1582.053571      362.250000   
42.0               -119.548039  35.310000  1730.039216      399.862745   
43.0               -119.330179  35.229821  1842.339286      413.232143   
44.0               -119.814902  35.575098  1862.490196      403.176471   
45.0               -119.499412  35.443333  1677.490196      365.137255   
46.0               -119.752439  35.587805  2031.609756      424.634146   
47.0               -119.384545  35.160909  1786.500000      449.318182   
48.0               -119.575294  35.479118  1648.882353      377.794118   
49.0               -119.795714  35.559524  1492.809524      331.666667   
50.0               -120.415625  36.627500  1779.312500      370.437500   
51.0               -120.091818  36.151818  1641.909091      373.818182   
52.0               -120.674451  36.427225  1831.219653      403.202312   

                     pop

Statistical Measures

In [56]:
csv_data.count()

longitude             3000
latitude              3000
housing_median_age    3000
total_rooms           3000
total_bedrooms        3000
population            3000
households            3000
median_income         3000
median_house_value    3000
dtype: int64

In [57]:
# mean value column wise
csv_data.mean()

longitude               -119.589200
latitude                  35.635390
housing_median_age        28.845333
total_rooms             2599.578667
total_bedrooms           529.950667
population              1402.798667
households               489.912000
median_income              3.807272
median_house_value    205846.275000
dtype: float64

In [58]:
# standard deviation column wise
csv_data.std()

longitude                  1.994936
latitude                   2.129670
housing_median_age        12.555396
total_rooms             2155.593332
total_bedrooms           415.654368
population              1030.543012
households               365.422710
median_income              1.854512
median_house_value    113119.687470
dtype: float64

In [59]:
# minimum value column wise
csv_data.min()

longitude              -124.1800
latitude                 32.5600
housing_median_age        1.0000
total_rooms               6.0000
total_bedrooms            2.0000
population                5.0000
households                2.0000
median_income             0.4999
median_house_value    22500.0000
dtype: float64

In [60]:
# max value column wise
csv_data.max()

longitude               -114.4900
latitude                  41.9200
housing_median_age        52.0000
total_rooms            30450.0000
total_bedrooms          5419.0000
population             11935.0000
households              4930.0000
median_income             15.0001
median_house_value    500001.0000
dtype: float64

In [61]:
# all statistical measures of dataframe
csv_data.describe()

longitude    latitude  housing_median_age   total_rooms  \
count  3000.000000  3000.00000         3000.000000   3000.000000   
mean   -119.589200    35.63539           28.845333   2599.578667   
std       1.994936     2.12967           12.555396   2155.593332   
min    -124.180000    32.56000            1.000000      6.000000   
25%    -121.810000    33.93000           18.000000   1401.000000   
50%    -118.485000    34.27000           29.000000   2106.000000   
75%    -118.020000    37.69000           37.000000   3129.000000   
max    -114.490000    41.92000           52.000000  30450.000000   

       total_bedrooms    population  households  median_income  \
count     3000.000000   3000.000000  3000.00000    3000.000000   
mean       529.950667   1402.798667   489.91200       3.807272   
std        415.654368   1030.543012   365.42271       1.854512   
min          2.000000      5.000000     2.00000       0.499900   
25%        291.000000    780.000000   273.00000       2.544000   
50%        437.000000   1155.000000   409.50000       3.487150   
75%        636.000000   1742.750000   597.25000       4.656475   
max       5419.000000  11935.000000  4930.00000      15.000100   

       median_house_value  
count          3000.00000  
mean         205846.27500  
std          113119.68747  
min           22500.00000  
25%          121200.00000  
50%          177650.00000  
75%          263975.00000  
max          500001.00000

Manipulating DataFrame

In [63]:
# adding column in datafreame
db_data['target'] = diabetes_dataset.target
db_data.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019907 -0.017646   151.0  
1 -0.039493 -0.068332 -0.092204    75.0  
2 -0.002592  0.002861 -0.025930   141.0  
3  0.034309  0.022688 -0.009362   206.0  
4 -0.002592 -0.031988 -0.046641   135.0

In [64]:
# removing a particular row
# axis = 0 for dropping row
# axis = 1 for dropping column
db_data.drop(index=0,axis=0)

age       sex       bmi        bp        s1        s2        s3  \
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
5   -0.092695 -0.044642 -0.040696 -0.019442 -0.068991 -0.079288  0.041277   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  target  
1   -0.039493 -0.068332 -0.092204    75.0  
2   -0.002592  0.002861 -0.025930   141.0  
3    0.034309  0.022688 -0.009362   206.0  
4   -0.002592 -0.031988 -0.046641   135.0  
5   -0.076395 -0.041176 -0.096346    97.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018114  0.044485   104.0  
439 -0.011080 -0.046883  0.015491   132.0  
440  0.026560  0.044529 -0.025930   220.0  
441 -0.039493 -0.004222  0.003064    57.0  

[441 rows x 11 columns]

In [65]:
# removing a particular column
db_data.drop('s1',axis=1)

age       sex       bmi        bp        s2        s3        s4  \
0    0.038076  0.050680  0.061696  0.021872 -0.034821 -0.043401 -0.002592   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.019163  0.074412 -0.039493   
2    0.085299  0.050680  0.044451 -0.005670 -0.034194 -0.032356 -0.002592   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.024991 -0.036038  0.034309   
4    0.005383 -0.044642 -0.036385  0.021872  0.015596  0.008142 -0.002592   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.002566 -0.028674 -0.002592   
438 -0.005515  0.050680 -0.015906 -0.067642  0.079165 -0.028674  0.034309   
439  0.041708  0.050680 -0.015906  0.017293 -0.013840 -0.024993 -0.011080   
440 -0.045472 -0.044642  0.039062  0.001215  0.015283 -0.028674  0.026560   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.027809  0.173816 -0.039493   

           s5        s6  target  
0    0.019907 -0.017646   151.0  
1   -0.068332 -0.092204    75.0  
2    0.002861 -0.025930   141.0  
3    0.022688 -0.009362   206.0  
4   -0.031988 -0.046641   135.0  
..        ...       ...     ...  
437  0.031193  0.007207   178.0  
438 -0.018114  0.044485   104.0  
439 -0.046883  0.015491   132.0  
440  0.044529 -0.025930   220.0  
441 -0.004222  0.003064    57.0  

[442 rows x 10 columns]

In [66]:
# locating a row using index value
db_data.iloc[2]

age         0.085299
sex         0.050680
bmi         0.044451
bp         -0.005670
s1         -0.045599
s2         -0.034194
s3         -0.032356
s4         -0.002592
s5          0.002861
s6         -0.025930
target    141.000000
Name: 2, dtype: float64

In [69]:
# locating a particular column
print(db_data.iloc[:,0]) # first column
print(db_data.iloc[:,1]) # second column
print(db_data.iloc[:,2]) # third column
print(db_data.iloc[:,-1]) # last column

0      0.038076
1     -0.001882
2      0.085299
3     -0.089063
4      0.005383
         ...   
437    0.041708
438   -0.005515
439    0.041708
440   -0.045472
441   -0.045472
Name: age, Length: 442, dtype: float64
0      0.050680
1     -0.044642
2      0.050680
3     -0.044642
4     -0.044642
         ...   
437    0.050680
438    0.050680
439    0.050680
440   -0.044642
441   -0.044642
Name: sex, Length: 442, dtype: float64
0      0.061696
1     -0.051474
2      0.044451
3     -0.011595
4     -0.036385
         ...   
437    0.019662
438   -0.015906
439   -0.015906
440    0.039062
441   -0.073030
Name: bmi, Length: 442, dtype: float64
0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...  
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: target, Length: 442, dtype: float64


Corelation in Pandas --> finding relation between columns

1. Positive Corelation --> if one column value increases with other
2. Negative Corelation --> if one column value decreases with other

In [71]:
db_data.corr()

age       sex       bmi        bp        s1        s2        s3  \
age     1.000000  0.173737  0.185085  0.335428  0.260061  0.219243 -0.075181   
sex     0.173737  1.000000  0.088161  0.241010  0.035277  0.142637 -0.379090   
bmi     0.185085  0.088161  1.000000  0.395411  0.249777  0.261170 -0.366811   
bp      0.335428  0.241010  0.395411  1.000000  0.242464  0.185548 -0.178762   
s1      0.260061  0.035277  0.249777  0.242464  1.000000  0.896663  0.051519   
s2      0.219243  0.142637  0.261170  0.185548  0.896663  1.000000 -0.196455   
s3     -0.075181 -0.379090 -0.366811 -0.178762  0.051519 -0.196455  1.000000   
s4      0.203841  0.332115  0.413807  0.257650  0.542207  0.659817 -0.738493   
s5      0.270774  0.149916  0.446157  0.393480  0.515503  0.318357 -0.398577   
s6      0.301731  0.208133  0.388680  0.390430  0.325717  0.290600 -0.273697   
target  0.187889  0.043062  0.586450  0.441482  0.212022  0.174054 -0.394789   

              s4        s5        s6    target  
age     0.203841  0.270774  0.301731  0.187889  
sex     0.332115  0.149916  0.208133  0.043062  
bmi     0.413807  0.446157  0.388680  0.586450  
bp      0.257650  0.393480  0.390430  0.441482  
s1      0.542207  0.515503  0.325717  0.212022  
s2      0.659817  0.318357  0.290600  0.174054  
s3     -0.738493 -0.398577 -0.273697 -0.394789  
s4      1.000000  0.617859  0.417212  0.430453  
s5      0.617859  1.000000  0.464669  0.565883  
s6      0.417212  0.464669  1.000000  0.382483  
target  0.430453  0.565883  0.382483  1.000000